---
apiVersion: v1
kind: Secret
metadata:
  name: nkendyal8-poi-backend-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-atl/nkendyal8-backend-gitops
